<?php

namespace Tests\Feature\User;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class checkUserIsAdminTest extends TestCase
{
    use DatabaseTransactions;
    use DatabaseMigrations;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * @test
     */
    function user_is_access_to_panel_admin()
    {
        $user = $this->createUser(1);
        $this->assertEquals(1, $this->isAdmin($user));
    }

    /**
     * @test
     */
    function user_is_not_access_to_panel_admin()
    {
        $user = $this->createUser(0);
        $this->assertEquals(1, $this->isNotAdmin($user));
    }

    protected function createUser($group)
    {
        $user = factory(User::class)->create([
            "group" => $group
        ]);

        return collect($user);
    }

    protected function isAdmin($user) {
        return $user->contains(function ($value, $key){
            return $value == 1;
        });
    }

    protected function isNotAdmin($user) {
        return $user->contains(function ($value, $key){
            return $value == 0;
        });
    }
}
