<?php

namespace Tests\Feature\Asset;

use App\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AssetTest extends TestCase
{

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @covers
     */
    function create_user_test()
    {
        $user = factory(User::class)->create();
        $this->assertEquals(1, $user->count());
    }

    /**
     * @test
     */
    function edit_user_test()
    {
        $user = factory(User::class)->create();
        $user->find(1)->update(["email" => "test@test.com"]);
        dd($user);

        $this->assertDatabaseHas($user, ["email" => "test@test.com"]);
    }
}
